### ISSUE TITLE
[Feature] GM_getResourceURL support data URL

### ISSUE THREAD

**Issue by polyproline** [scriptscat/scriptcat#84]
Data url is more efficient in DOM.
https://github.com/violentmonkey/violentmonkey/issues/1436
https://github.com/violentmonkey/violentmonkey/pull/1438

**Comment by CodFrm** [comment]
default output of GM_getResourceURL is data url,set the second parameter to output blob url

**Comment by cyfung1031** [comment]
Just a remarks:
This was totally a mistake made in Violentmonkey.
`GM_getResourceURL` was designed to obtain the raw data represented in url format, which is dataURI base64
This should be totally not related to Blob URL. Blob URL is not designed for raw data representation.
To cover the mistake, VM added 2nd parameter `isBlobUrl` to represent the result should be in the blob url format.

However, blob url shall be managed carefully (by the userscript developer) since it will reserve a memory block in the browser to store the entire file contents.
